config/routes.rb
RankV2::Application.routes.draw do
  post "algorithm/save"
  post "algorithm/saveas"
  get "algorithm/delete"
  get "algorithm/load"
  devise_for :users
  get '/controls/updatecsvs', to: 'controls#updatecsvs'
  get '/controls/noaccess', to: 'controls#deniedAccess'
  post '/controls/uploadteams', to: 'controls#uploadteams'
  post '/controls/uploadgames', to: 'controls#uploadgames'
  post '/controls/uploadperformances', to: 'controls#uploadperformances'
  post '/controls/uploadconferences', to: 'controls#uploadconferences'
  post '/controls/cacheall', to: 'controls#cacheall'
  post '/controls/uploadzip', to: 'controls#uploadzip'

  get '/create', to: 'ranks#write'
  get '/req_data', to: 'ranks#getData'
  get '/dataCache', to: 'ranks#dataCache'
  get '/firstYearCache', to: 'ranks#firstYearCache'
  get '/ranks/clearCache', to: 'ranks#clearCache'
  get '/ranks/codeFrame', to: 'ranks#ranksFrame'
  get '/ranks/shareCalcFrame', to: 'ranks#shareCalcFrame'
  post '/shares/create', to: 'shares#create'
  get '/shares/loading', to: 'shares#loading'
  get '/shares/:encodedID' => 'shares#view'

  root 'ranks#write'

  devise_scope :user do
      get "login", :to => "devise/sessions#new"
  end

end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController

	before_filter	:check_for_admin
	skip_before_action :check_for_admin, only: [:deniedAccess]

	#before_filter :check_for_year
	#skip_before_action :check_for_year, only: [:updatecsvs]

        before_filter :validate_year
        skip_before_action :validate_year, only: [:uploadteams, :updatecsvs, :uploadzip]

        def uploadzip
            check_for_year
            puts "hello"
            lister = Proc.new {|file| puts file}
            Zip::ZipFile.foreach(params[:file].path, &lister)

            Zip::ZipFile.open(params[:file].path) do |zipfile|
                team_file = zipfile.find_entry("team.csv")
                game_file = zipfile.find_entry("game.csv")
                performance_file = zipfile.find_entry("team-game-statistics.csv")
                conference_file = zipfile.find_entry("conference.csv")

                if team_file == nil || game_file == nil || performance_file == nil || conference_file == nil
                    flash[:notice] = "Failed to open all files in #{zipfile.name}"
		    redirect_to '/controls/updatecsvs'
                end

                
                team_filename = zipfile.name + '_' + team_file.to_s
                team_file.extract(team_filename)
                num = Team.import(File.new(team_filename), params[:year])

                game_filename = zipfile.name + '_' + game_file.to_s
                game_file.extract(game_filename)
                num = Game.import(File.new(game_filename), params[:year])

                performance_filename = zipfile.name + '_' + performance_file.to_s
                performance_file.extract(performance_filename)
                num = Performance.import(File.new(performance_filename), params[:year])

                conference_filename = zipfile.name + '_' + conference_file.to_s
                conference_file.extract(conference_filename)
                num = Conference.import(File.new(conference_filename), params[:year])
                flash[:notice] = "Succesfully extracted #{zipfile.name}"
		redirect_to '/ranks/clearCache'
            end
        end


	def uploadteams
                check_for_year
		num = Team.import(params[:file], params[:year])
		flash[:notice] = "Succesfully added #{num} teams"
		redirect_to '/controls/updatecsvs'
	end

	def uploadgames
		num = Game.import(params[:file], params[:year])
		flash[:notice] = "Succesfully added #{num} games"
		redirect_to '/controls/updatecsvs'
	end

	def uploadperformances
		num = Performance.import(params[:file], params[:year])
		flash[:notice] = "Succesfully added #{num} performances"
		redirect_to '/controls/updatecsvs'
	end

	def uploadconferences
		num = Conference.import(params[:file], params[:year])
		flash[:notice] = "Succesfully added #{num} conferences"
		redirect_to '/controls/updatecsvs'
	end

        def cacheall
            Rails.cache.clear
            weeksMap = Season.getWeeksMap
            weeksMap.each do |year, array|
                array.each do |week|
                    Team.getData(year,week[1])
                end
            end
            redirect_to '/ranks/dataCache'
        end

	def updatecsvs
		#@text = Performance.findTeamPoints('Stanford')
		#@sampleJSON = Team.getAllJSON
	end


	private

        def validate_year
            if params[:year] != nil && !Season.exists?(params[:year]) 
                flash[:error] = "That year doesn't exist."
		redirect_to '/controls/updatecsvs'
            end
        end


	def check_for_year
		if params[:year] != nil && Season.exists?(params[:year]) == nil
			y = Season.new
			y.year = params[:year]
			y.save
		end
	end

	def performance_params
	  params.require(:performance).permit(:points)
	end

	def check_for_admin
		unless current_user.try(:admin?)
			flash[:error] = "You're not an admin, sorry."
			redirect_to '/controls/noaccess'
		end
	end

end

app/views/controls/deniedAccess.html.erb
<h1>Real sorry, you can't be here!</h1>

app/views/controls/updatecsvs.html.erb
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <script>
$(document).ready(function(){
    $('#zip-upload').on('click',function() {  
            console.log('submitting');
        var valuesToSubmit = new FormData($('#zip-form')[0]);//.serialize();
        $.ajax({
            type: 'POST',
            url: $('#zip-form').attr('action'), //sumbits it to the given url of the form
            data: valuesToSubmit,
            cache: false,
            contentType: false,
            processData: false
            //dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
            }).success(function(json){
                alert('Success!');
                console.log(json);
            //act on result.
        });
        return false; // prevents normal behaviour
        });

    $('form[data-remote')
        .on('ajax:success', function(e, data, status, xhr){
            alert(data);
        })
        .on('ajax:error', function(e, data, status, xhr){
            alert(e);
            alert(data);
            });
});
</script>

<p>Zipped Folder</p>
<%= form_tag  controls_uploadzip_path, id: 'zip-form',  multipart: true,remote: true do %>
	<%= file_field_tag	:file %>
		Year:
                <%= text_field_tag	:year %>
	<% submit_tag :update %>
<% end %>
                <button style="width: 30px; height: 30px" id="zip-upload">ZIP</button>

<p>Teams</p>
<%= form_tag  controls_uploadteams_path, multipart: true do %>
	<%= file_field_tag	:file %>
		Year:
	<%= text_field_tag	:year %>
	<%= submit_tag :update %>
<% end %>

</br>
<p>Games</p>
<%= form_tag  controls_uploadgames_path, multipart: true do %>
	<%= file_field_tag	:file %>
	Year:
	<%= text_field_tag	:year %>
	<%= submit_tag :update %>
<% end %>

</br>
<p>Performances</p>
<%= form_tag  controls_uploadperformances_path, multipart: true do %>
	<%= file_field_tag	:file %>
	Year:
	<%= text_field_tag	:year %>
	<%= submit_tag :update %>
<% end %>
</br>
<p>Conferences</p>
<%= form_tag  controls_uploadconferences_path, multipart: true do %>
	<%= file_field_tag	:file %>
	Year:
	<%= text_field_tag	:year %>
	<%= submit_tag :update %>
<% end %>

<p>Update Cache</p>
<%= form_tag  controls_cacheall_path, remote: true do %>
	<%= submit_tag :Recache%>
<% end %>