config/routes.rb
RankV2::Application.routes.draw do
  post "algorithm/save"
  post "algorithm/saveas"
  get "algorithm/delete"
  get "algorithm/load"
  devise_for :users
  get '/controls/updatecsvs', to: 'controls#updatecsvs'
  get '/controls/noaccess', to: 'controls#deniedAccess'
  post '/controls/uploadteams', to: 'controls#uploadteams'
  post '/controls/uploadgames', to: 'controls#uploadgames'
  post '/controls/uploadperformances', to: 'controls#uploadperformances'
  post '/controls/uploadconferences', to: 'controls#uploadconferences'
  post '/controls/cacheall', to: 'controls#cacheall'
  post '/controls/uploadzip', to: 'controls#uploadzip'

  get '/create', to: 'ranks#write'
  get '/req_data', to: 'ranks#getData'
  get '/dataCache', to: 'ranks#dataCache'
  get '/firstYearCache', to: 'ranks#firstYearCache'
  get '/ranks/clearCache', to: 'ranks#clearCache'
  get '/ranks/codeFrame', to: 'ranks#ranksFrame'
  get '/ranks/shareCalcFrame', to: 'ranks#shareCalcFrame'
  post '/shares/create', to: 'shares#create'
  get '/shares/loading', to: 'shares#loading'
  get '/shares/:encodedID' => 'shares#view'

  root 'ranks#write'

  devise_scope :user do
      get "login", :to => "devise/sessions#new"
  end

end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	respond_to	:html, :json
        caches_page     :dataCache, :firstYearCache
	def write
		@signed_in = false
		@saveArray = Array.new
		@curAlg = nil
		if user_signed_in?
			@signed_in = true
			saves = current_user.algorithms
			if current_user.current_alg_id
				if Algorithm.exists?(current_user.current_alg_id)
					@curAlg = Algorithm.find(current_user.current_alg_id).to_json
				end
			end
			saves.each do |alg|
				@saveArray << alg.getAlgorithmOption
			end
			@saveArray.sort! {|a,b| a.last_time <=> b.last_time}
                end
                @saveArray = @saveArray.to_json

		@algorithm = Algorithm.new
		@new_algorithm = Algorithm.new

                #@weeksMap = Season.getWeeksMap.to_json
                #@dataMap = Season.getAllData.to_json

	end

	def getData
#		@teamJSON = Season.find(year => params[:year]).teams.to_json
#		@teamJSON = Team.getData(params[:year], params[:week])
#		render	:json => @teamJSON
#		return
	   
            render json: Team.getData(params[:year], params[:week])
            return
	end

        def dataCache
            logger.info "Cache miss dataCache page"
            @weeksMap = Season.getWeeksMap.to_json
            @dataMap = Season.getAllData.to_json
	    render :layout => false
        end

        def firstYearCache
            @weeksMap = Season.getWeeksMap.to_json
            @dataMap = Season.getLatestSeason.to_json
            render :layout => false
        end


        def clearCache
            expire_page :action => 'dataCache'
            expire_page :action => 'firstYearCache'
            redirect_to '/controls/updatecsvs'
        end

	def ranksFrame
		render :layout => false
	end
end

app/views/ranks/dataCache.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <%= hidden_field_tag "weeks-map", @weeksMap, {:id => 'weeks-map' }%>
        <%= hidden_field_tag "data-map", @dataMap, {:id => 'data-map'}%>
    </body>
</html>

app/views/ranks/ranksFrame.html.erb
<!DOCTYPE HTML>
<html>
    <head>
        <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
        <%= javascript_include_tag 'separate-ranksFrame-main' %>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="rankingsWrapper">
            <div class="rankings">

            </div>

        </div>
    </body>

</html>

app/views/ranks/write.html.erb
<%= javascript_include_tag 'separate-write-main' %>
<% stylesheet_link_tag 'selectric.css' %>

<div class="modalBackground"id="loginBackground"></div>
<div id="loginDialog">
    <p>You need to <%= link_to('login', new_user_session_path) %>!</p>
</div>

<div class="modalBackground" id="helpBackground"></div>
<div id="helpDialog">
    <p>
        <h3>Confused?</h3>
        <h4>New to Javascript?</h4>
                <a href="http://www.codecademy.com/tracks/javascript">Here's your first stop</a>. Lessons 1 - 11 will be useful!
        <h4>JS Vet?</h4>
        <a href="http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers">Open up your javascript console.</a>
        Type 'teams' (no quote marks). This is the object passed into the main method.</br>
        Your job is to sort it.<br/>
        <h4>What libraries are available?</h4>
        <a href="http://jquery.com/">jQuery</a> and <a href="http://www.jstat.org/">jStat</a> are both loaded.
    </p>
</div>


<div class="modalBackground" id="shareBackground"></div>
<div class="dialog" id="shareDialog">
    <p>
        <h1>Sharing is currently under development!</h1>
        <p>This feature opens up a potential hornets' next of security issues.</p>
        <p>Until I can get some technical aspects nailed down, we're gonna err on the safe side. If you've got some expertise and would like to
            help out, please reach out!
        </p>
    </p>
</div>

<div class="modalBackground" id="infoBackground"></div>
<div id="infoDialog">
    <p>
            <h1>CFBRanker</h1>
            <h6>version 0.01</h6>
            For those of us who are pretty sure we're way smarter than
            <a href="http://en.wikipedia.org/wiki/Jeff_Sagarin">Jeff Sagarin</a>,
            <a href="http://www.cnn.com/2010/TECH/web/12/07/bcs/">Jeff Anderson and Chris Hester</a>,
            <a href="http://sports.espn.go.com/espn/page2/story?page=jones/061208">Richard Billingsley</a>,
            <a href="http://www.colleyrankings.com/matrate.pdf">Wesley Colley</a>,
            <a href="http://www.gobblercountry.com/2010/11/5/1789521/talking-college-football-computer-rankings-with-kenneth-massey">Ken Massey
            </a>, and
            <a href="http://articles.latimes.com/2003/nov/10/sports/sp-bcs10">Peter Wolfe</a>.
    </p>
    <p>
            Please <a href="mailto:danieloneel@gmail.com">email me</a> if you need help with or have ideas about this site. Also if       you're way better at CSS than me (this is probably you), drop me a line, there's obviously a lot to be done.
            </br>
            </br>
            Built with:
            <ul>
                    <li><a href="http://rubyonrails.org/">Rails 4</a></li>
                    <li><a href="http://ace.c9.io/">Ace</a></li>
                    <li><a href="http://ionicons.com/">Ionicons</a></li>
                    <li><a href="http://jquery.com/">jQuery</a></li>
                    <li><a href="http://www.noisetexturegenerator.com/">Noise Texture Generator</a></li>
                    <li><a href="http://fgnass.github.io/spin.js/">Spin.js</a></li>
                    <li><a href="http://www.jstat.org">jStat</a></li>
                    <li><a href="http://www.cfbstats.com/">CFBStats.com</a></li>
                    <li><a href="http://www.dafont.com/friday-night-lights.font?sort=date">Friday Night Lights Font</a></li>
            </ul>
    </p>

</div>


<div class="interface">
    <div class="leftSide">
	    <div class="saveBar">
        </div>
        <div class="workPane">
            	<div id="codeEditorContainer">
            	</div>
                <div class="controlBar">
                    <table class="controlsCenteringDiv">
                        <tbody>
                            <tr>
                                <td><a class="controlButton" id="saveButton" onclick="saveCode()">Save</a></td>
                                <td><a class="controlButton" onclick="runAlgorithm()">Run</a></td>
                                <td><label class="selectBoxLabel" >Year</label></td>
                                <td><select  id="yearBox">Season</td>
                                <td></select></td>
                                <td><label class="selectBoxLabel" >Week</label></td>
                                <td><select  id="weekBox">Week</td>
                                <td></select></td>
                                <td><a class="controlButton" id="shareButton">Share</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
    <div class="rightSide">
        <iframe sandbox='allow-scripts allow-popups allow-same-origin'  class="resultsPanel">
        </iframe>
    </div>
</div>

<div class="hidden">
<%= form_for @algorithm, html: {id:     'saveForm', class: 'hidden'}, remote: true, url: algorithm_save_path do |f|     %>
    <%= f.text_area :code, :class => 'hidden', :id => 'save_form_code' %>
    <%= f.hidden_field :id, :id     => 'save_form_id' %>
    <% f.submit :Save %>
<% end %>


<%= form_for @new_algorithm, html: {id: 'saveAsForm'}, remote: true, url: algorithm_saveas_path do |f| %>
    <%= f.text_area :code, :class => 'hidden', :id => 'saveas_form_code' %>
    <%= f.label 'Name:' %>
    <%= f.text_field :save_name, :id => 'saveas_form_name' %>
    <%= f.submit :Save %>
<% end %>
</div>

<%= hidden_field_tag "signed-in", @signed_in, {:id => 'signed-in' }%>
<%= hidden_field_tag "save-array", @saveArray, {:id => 'save-array' }%>


<iframe sandbox='allow-same-origin' class="hidden" id="data-cache-page" src="/firstYearCache">
</iframe>

<iframe sandbox='allow-same-origin' class="hidden" id="all-data-cache-page">
</iframe>
<div class="hidden">
    <div class="franchise-font">
        Force fetching of font.
    </div>

    <div class="team-logo">
        Force fetching of logo image.
    </div>
</div>